name: "Build Debug Version"

on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test

jobs:
  build:
    name: Build Debug Version
    runs-on: macos-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set Up Java
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      # 3. Set Up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      # 4. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5. Build Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug

      # 6. Build Debug App Bundle (AAB)
      - name: Build Debug App Bundle
        run: flutter build appbundle --debug

      # 7. Build Debug IPA (iOS)
      - name: Build Debug IPA
        run: flutter build ipa --debug --no-codesign

      # 8. Compress iOS Build Outputs
      - name: Compress iOS Build Outputs
        run: |
          cd build
          tar -czf ios_build_debug.tar.gz ios

      # 9. Upload Artifacts
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debug-Builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/bundle/debug/app-debug.aab
            build/ios_build_debug.tar.gz
